### ISSUE TITLE
mednafen saturn libretro core , not work for me

### ISSUE THREAD

**Issue by nandobyker** [libretro-mirrors/beetle-saturn-libretro#103]
I have config the bios files on the system folder
those are the bios i have
 sega_101.bin 
 mpr-17933.bin | 
 mpr-18811-mx.ic1
 mpr-19367-mx.ic1 

The King of Fighters '95 (Saturn) (JE) [!] ROM Cartridge ( i renamed to mpr-18811-mx.ic1 ) and it detect the bios

when i load the core , i open the .cue file to load the rom and it crash

what i had did wrong ?

**Comment by hiddenasbestos** [comment]
Can you post a bit more information about what operating system you're running on? What version of the core you're using? (the "a54325a42" looking number displayed on the bottom-left of the screen when the core is loaded)

What you say crash do you mean the whole of RetroArch stops, or do you just get a black screen? does it go to the Saturn bios screen with the CD Player controls?

Do all games you try cause it to crash?

**Comment by nandobyker** [comment]
Im running windows 10 PRO  v 1709   OS BUILD 1629.125
with some research i managed to run the mednafen saturn v0.9.48 a0a6dad
it was 2 problem
the first one it was the video filter for default  was on scale 2x and it crashed , then i changed to no filter and it fixed
the second was the in the rom folder only work with .bin and .cue file (not iso) i had to delete the .nfo for some reason it not load the rom
then it worked although it run a little slow

then i try find another solution for that problem 
i try to load  yabause v0.9.14  c55eef9
 I try every step i did before but it not work
 I heard the the bios is saturn_bios.bin ,i did the video config with no filter and rom folder correctly   it only show a black screen with save state then it freeze

any help for this?

**Comment by hiddenasbestos** [comment]
Glad you got it working. Yes only cue/bin, ccd and chd formats are supported by this core.

Please close this issue if you feel it is now resolved.

Please post yabuse issues here: https://github.com/libretro/yabause
