### ISSUE TITLE
no items showing for valid .cue ?

### ISSUE THREAD

**Issue by gingerbeardman** [libretro-mirrors/beetle-saturn-libretro#122]
my files work in OpenEmu.
filtering is off in Directory Settings.

`Waialae no Kiseki - Extra 36 Holes (Japan).cue`

contents 
```
FILE "Waialae no Kiseki - Extra 36 Holes (Japan) (Track 1).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "Waialae no Kiseki - Extra 36 Holes (Japan) (Track 2).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
```

<img width="752" alt="screen shot 2018-05-24 at 11 50 21" src="https://user-images.githubusercontent.com/49612/40481251-bb678a16-5f48-11e8-9bf1-c6529772a9e0.png">

"no items" displayed (shown) and "failed to load content" OSD message (not shown)
<img width="752" alt="screen shot 2018-05-24 at 11 51 29" src="https://user-images.githubusercontent.com/49612/40481281-d5d7e36e-5f48-11e8-9f31-9d6f85cac6fe.png">

**Comment by hiddenasbestos** [comment]
AFAIK this core only supports single .bin/.cue pairs - looks like you'll need to combine those two tracks into one image (I use daemon tools to mount it and ImgBurn to write out a cue/bin pair)

**Comment by gingerbeardman** [comment]
OK I'll try that, thanks

**Comment by gingerbeardman** [comment]
I used Liquid CD to mount the cue+2 bin files and write out as cue+1 bin file. Useful!

But it still doesn't work. Same issue "no items" display and "failed to load content" OSD message when selecting the cue.

**Comment by gingerbeardman** [comment]
I have tried multiple games
and also tried moving games to a path name with no spaces or odd characters

still no joy

odd that the games work in OpenEmu, whose Saturn core is based on same code, with no modification.

**Comment by gingerbeardman** [comment]
Oops. I forgot to put the 2x bios files in the system folder.

I would expect a better error message in this instance?

**Comment by hiddenasbestos** [comment]
hah, I've done that :)

That's a bit of a deficiency in the libretro api - you ask it to "load a game" and it says yes/no. Requires the front-end to have meta-data about the core to check things like bios files exist, etc. Maybe something for API v2 ...
