### ISSUE TITLE
Virtual Gun (Not Work)

### ISSUE THREAD

**Issue by ToniBC** [libretro-mirrors/beetle-saturn-libretro#133]
Hello, I put it separately since I mentioned it in another post.

The support for pistol, which in Mednafen Standalone works, for example, in the game House of the Dead, in libretro the cursor remains in the left, moves by the left line of up-down, but nothing more.

I do not know if it's a libretro problem or a specific option, but the standalone version works well and not here.

I mention it more than anything because as you comment, you have to report the failures so that they remain proof of them.

Thank you.

**Comment by hiddenasbestos** [comment]
Yes I can confirm this is broken in my own homemade (non-RetroArch) front-end for Virtua Cop 2 and House of the Dead.

Very likely I broke something during the merge - either in the VDP2 code, or the gun input code.

**Comment by hiddenasbestos** [comment]
Fixed in #135
