### ISSUE TITLE
Enemy Zero - Multiple disks. Do not load the disc.

### ISSUE THREAD

**Issue by alexb3d** [libretro-mirrors/beetle-saturn-libretro#14]
Mednafen Saturn 0.9.39.1 (Retroarch testing)
- Disk Cycle Tray Status: Ejected virtual disk tray
- Disk Indes 1: **Failed to set disk 2 of 4**
- Disk Image Append: **Failed to set disk 5 of 5**

I tried it on Windows. Mednafen 0.9.39.1:
- F8: Virtual CD Drive: Tray Open
- F6: Disc 2 of 4 selected
- F8: Virtual CD Drive: Tray Closed (Disc 2 of 4)
  **Does nothing.**

This is the file "Enemy Zero (USA).m3u"
Enemy Zero (Disc 0 of 4) (USA) (DW0775).cue
Enemy Zero (Disc 1 of 4) (USA) (DW0775).cue
Enemy Zero (Disc 2 of 4) (USA) (DW0775).cue
Enemy Zero (Disc 3 of 4) (USA) (DW0775).cue

Am I doing something wrong or is a program error?

**Comment by sobkas** [comment]
Well inside libretro.cpp there are some #if 0 that disable hacky multi disk support so it's program "feature" rather than error.

**Comment by alexb3d** [comment]
It seems to be a mistake by Mednafen. I have not tried other games.

**Comment by hiddenasbestos** [comment]
Hi, I believe this is now fixed.
