### ISSUE TITLE
CD Image Cache setting not working

### ISSUE THREAD

**Issue by Epicbeardman** [libretro-mirrors/beetle-saturn-libretro#144]
## Description

Beetle Saturn for RetroArch does not load the complete image into RAM when the `CD Image Cache` setting is enabled in the core options (`beetle_saturn_cdimagecache = "enabled"` in `retroarch-core-options.cfg`).

The standalone version of Mednafen Saturn **does** cache the complete image when the line `cd.image_memcache 1` is present in `mednafen.cfg`. Versions 1.22.1 and 1.22.2 of Mednafen were tested.

### Expected behaviour

The complete image should be loaded into RAM when the `CD Image Cache` setting is enabled in the core options.

### Actual behaviour

The complete image is not loaded into RAM when the `CD Image Cache` setting is enabled in the core options.

### Steps to reproduce the bug

1. Load the Beetle Saturn core.
2. Load a large Saturn game that would otherwise result in a noticeable increase in RAM usage.
3. Under `Quick Menu -> Options`, enable `CD Image Cache (restart)`.
4. Restart the game.
5. View the RAM usage of RetroArch.

### Version
- RetroArch v1.7.7
- Git version: `8c17f12f97`
- Build date: `May 8 2019`
- Compiler: `MinGW (7.3.0) 64-bit`
- Beetle Saturn v1.22.1-052f6d6

### Environment information
- OS: `Windows 10 x64 Build 17763 (v10.0)`

**Comment by linearity** [comment]
This is an issue for anybody trying to load images from another machine on a home network.

I'm not familiar with this code, but it seems in [disc.cpp](https://github.com/libretro/beetle-saturn-libretro/blob/8a65943bb7bbc3183eeb0d57c4ac3e663f1bcc11/disc.cpp) that the `image_memcache` parameter to the loading procedures is always equal to `false`.
