### ISSUE TITLE
Update core to 1.29.0

### ISSUE THREAD

**Issue by ToniBC** [libretro-mirrors/beetle-saturn-libretro#155]
Mednafen was recently updated with several corrections of this emulator and it would be nice to include them to improve those small errors. I don't know if some have already been applied, but since the core only reflects that it is in 1.22.2, they supposedly were not added.

After 1.22.2 there are several changes that would be good to include in the core to improve emulation.

- SS: Slowed down SCU DMA from SDRAM/SH-2 bus slightly, though I'm not sure what is the origin of the measured overhead/slowdown on a Saturn. Fixes FMV flickering in "Lunar".
- SS: Added partial emulation(CS0 and CS1, SH-2 non-DMA accesses and SCU DMA accesses) of the timing effects of the SCU A-bus configuration registers.
- SS: Added "Tech Saturn 1997.6" to the internal database of games for which 1MiB RAM cart emulation is enabled, for its "Groove on Fight" demo.
- SS: Implemented a crude simulation of the VDP1 command execution slowdown that occurs when an SH-2 CPU writes to VDP1 RAM or registers, activated via the horrible hacks mechanism; fixes text flickering in "Arcade's Greatest Hits", most rescue text flickering in "Burning Rangers"(at least on the first stage), graphical glitches in "Whizz", and some of the graphical glitches in "All-Star Baseball 97".
- SS: Added a horrible hack to fix the hang in "Fighters Megamix" that occurred after the intro FMV played(or was interrupted).
- SS: Added a horrible hack to fix the hang at the end of disc 1 of "Grandia".
- SS: Added a per-game horrible hacks mechanism.
- SS: Added "Albert Odyssey" to the internal database of games to use full cache emulation with, to fix battle text truncation.
- SS: Added "Die Hard Trilogy", "GeGeGe no Kitarou", "Nobunaga no Yabou Shouseiroku", "Space Jam" to the internal database of games to use full cache emulation with, to fix hangs/crashes.
- SS: Added "Gex" and "Slam 'n Jam 96" to the internal database of games to use full cache emulation with, to fix minor FMV glitches.
- SS: Added "Policenauts" to the internal database of games to use full cache emulation with, to fix screen flickering on disc 2.
- SS: Full cache emulation(enabled via database) now also enables emulation of SH-2 WB/EX pipeline stalls.
- SS: Tweaked the kludgey CPU instruction read/write penalty during SH-2 DMA to be higher in some circumstances; fixes major graphical glitches in the later stages of "Shienryu" when on arcade mode.
- SS: Added "Dragon Force II" to the internal database of games to use the data cache read bypass kludge with, to fix major game logic errors during battles.
- SS: Added "Formula Grand Prix - Team Unei Simulation" to the internal database of games to use the data cache read bypass kludge with, to fix a hang after the title screen.
- SS: Added "Virtual Mahjong" to the internal database of games to use the data cache read bypass kludge with, to fix graphical glitches on the character select screen.
- SS: Added "Thunder Force Gold Pack 2" to the internal database of games to use the data cache read bypass kludge with, to fix quasi-random hangs when pausing the game in "Thunder Force AC".
- SS: Corrected the value the SCU DMA mode registers are initialized to on reset.
- SS: Added "Thunder Force Gold Pack 1" to the internal database of games to use the data cache read bypass kludge with, to fix explosion graphic glitches in "Thunder Force III".
- SS: Fixed a bug that could cause erroneous VDP1 framebuffer erasure when the lower Y coordinate for the erase window was too large.
- SS: Added "Ronde" to the internal database of games to use the data cache read bypass kludge with, to fix missing graphics on the title screen and main menu.
- SS: Added "Shunsai" to the internal database of games to use the data cache read bypass kludge with, to fix various graphical glitches.
- SS: Implemented more complete emulation of SCSP's buggy linear interpolation on FM carrier slots.
- SS: Fixed a minor VDP1 rendering inaccuracy with non-rectangular sprites and polygons.
- SS: Fixed excessive CPU usage during the FMV in "Dark Seed II".
- SS: Fixed hang after defeating the final boss in "Rayman".
- SS: Fixed hang after the Meribia singer's singing in "Lunar".
- SS: Fixed missing graphics during the attract mode in "Virtua Cop".
- SS: Fixed garbage horizontally-stretched sprite in the Christmas-themed stage in "Christmas NiGHTS into Dreams".
- SS: Fixed dialogue text truncation in "Senken Kigyouden".
- SS: Significantly reduced graphical glitching in "Virtua Fighter" and "Virtua Fighter Remix".

1.26.0

- SS: Fixed startup hang in the Europe releases of "Virtua Cop" and "Virtua Cop 2".
- SS: Fixed startup hang in the USA release of "Independence Day".
- SS: Fixed hang in "QuoVadis".
- SS: Fixed hang in "Kidou Senkan Nadesico: Yappari Saigo wa Ai ga Katsu".
- SS: Fixed crash/hang in "Hop Step Idol".
- SS: Fixed startup abort to CD player screen in "Break Point" and "DJ Wars".
- SS: Fixed hang of finite duration that sometimes occurred when trying to skip FMVs in "Dragon Force II" and "World Cup France '98: Road to Win".
- SS: Fixed major sound glitches during gameplay in "Gunbird" after starting a game after exiting from the illustration gallery.
- SS: Fixed dialogue voice audio being cut off prematurely in "Paneltia Story".
- SS: Fixed missing graphics in the intro of "Magical Drop III".
- SS: Fixed missing background layer graphics on disc 2 of "Mahjong Doukyuusei Special".
- SS: Fixed glitchy ship sprite in the ending sequence of "Thunder Force III" in "Thunder Force Gold Pack 1".
- SS: Fixed FMV tearing in "Ys II" of "Falcom Classics II".
- SS: Fixed FMV tearing in "In the Hunt".
- SS: Fixed minor FMV glitches in "3D Baseball", "The Crow", "NBA Action", "NFL Quarterback Club 96", "Solar Eclipse", and "Titan Wars".
- SS: Fixed FMV glitches in "NFL Quarterback Club 97".
- SS: Fixed FMV glitches in the Japan and USA releases of "Virtua Fighter Kids".
- SS: Fixed intro FMV ending too soon in "Yu-No".
- SS: Fixed glitchy frames on the Konami intro arm sprite in "Tokimeki Memorial: Forever With You".
- SS: Fixed graphical glitches on the save and load screens in "Horror Tour".
- SS: Fixed glitchy rotation-zoom effect in "Corpse Killer".
- SS: Fixed blank game over screen in "Doraemon: Nobita to Fukkatsu no Hoshi".
- SS: Fixed glitches when character graphics change in "Mujintou Monogatari R: Futari no Love Love Island".
- SS: Fixed character portrait graphical glitch after entering the character select screen in "Zero Divide".
- SS: Further reduced graphical glitching in "Virtua Fighter Remix".
- SS: Fixed most rock face graphical glitches in "The Lost World: Jurassic Park".
- SS: Fixed most graphical glitches with the player's robot in "Wolf Fang SS: Kuuga 2001".

1.27.0

- SS: Fixed major audio problems in "Lunar" during boss battles, due to the sound CPU crashing inaccurately during game bootup and corrupting SCSP DSP registers. Note that this fix will not affect existing save states made within the game.

1.27.1

- SS: Added "Herc's Adventures" to the internal database of games to enable SH-2 read/write VDP1
	draw slowdown with, to fix a few graphical glitches.

1.28.0

- SS: The emulated reset button mapped to Mednafen's reset command key(F10 default) will now respect the "input.ckdelay" setting.
- SS: The VA0/VA1 motherboard's memory mapping behavior for Low-RAM is now emulated instead of VA2's, to fix a crash in "Myst" in the generator room.
- SS: Fixed unresponsive input in "Discworld".
- SS: Fixed startup abort to CD player screen in the Europe and USA releases of "Primal Rage".
- SS: Fixed abort to CD player screen when trying to start a game demo in Gremlin Interactive's "Demo Disc".
- SS: Fixed inability to skip the intro FMV in "Senkutsu Katsuryu Taisen: Chaos Seed".
- SS: Fixed flickering title screen in the "Saturn Super Vol. 2" demo of "Golden Axe: The Duel".
- SS: Fixed a regression introduced in 1.26.0-UNSTABLE that broke the CD audio player in the North America/Europe BIOS.
- SS: Implemented emulation of the CD block Scan command, to allow the scan forward/backward functionality in the BIOS's CD audio player to work.
- SS: Fixed a bug in the CD seek handling code that could cause more emulator frame pacing and sound buffer underrun issues than strictly necessary when CD image memory caching is not enabled, the default.
- SS: Corrected a few inaccuracies in the relative timing between different SCSP EG rates and between different SCSP timer prescaler rates(probably with negligible audible effects in commercial game sound drivers).

I comment as you recommended to me to be reflected and appear as a pending task.

Many thanks for your work.

**Comment by Mr-Jake** [comment]
@hiddenasbestos Would you have an opportunity to update the core to 1.23.0? Many thanks for all your previous improvements and updates to the core.

**Comment by hiddenasbestos** [comment]
> @hiddenasbestos Would you have an opportunity to update the core to 1.23.0? Many thanks for all your previous improvements and updates to the core.

Thanks for tagging me, I'd missed this one. I'm pretty busy atm but that's a nice lot of changes so I'll see if I can find some time to fit it in. Hopefully the internals aren't too massively changed and I can pull out the relevant pieces.

**Comment by ToniBC** [comment]
Version 1.24.2 just came out with several more fixes for Saturn of the best emulator at the moment that we have available. I only put it to refresh the subject, because it would be good to give a review to the code and not leave it too outdated. The last update was done relatively quickly, but now it is being left far behind and there are more and more things to implement.

Thank you very much to all who collaborate, I insist, it is only to refresh the topic, as a reminder.

**Comment by ToniBC** [comment]
They released a new version of Mednafen, again focused on the Saturn emulation with more bugs fixed. Each time this core is lagging behind.

I insist, this is just to inform.

**Comment by ToniBC** [comment]
The evolution of this emulator continues to advance, but the core of the libretro seems to have stagnated. I am remembering the news, some of them will not be necessary surely, but the vast majority will.

I see that they are updating several cores, it would be good to update this one too, little by little.

Thanks for your work.

**Comment by ToniBC** [comment]
I see several bugs that are reporting because the core is not updated. We are going through the 1.27.0 Standalone and we continue basically in the 1.22.2. All the advances in this, which is the best core, are being lost. It would be good to spend a little time and update the core a bit, since many are those who use Retroarch but there are a little forgotten cores.

**Comment by hiddenasbestos** [comment]
FWIW I did do some sync work on this core 6 months ago, which takes it to 1.24.3 - you can find that here, it might work with RetroArch, I have no idea:
https://github.com/hiddenasbestos/beetle-saturn-libretro/tree/gridc

The unfortunate problem was that I didn't do my mednafen upgrade in a way that was synced to the changes made to this core since I last did an update, so it's a rather messy situation where I upgraded the mednafen version this RetroArch core is at, but on an older version of the LibRetro core. If someone wants to take my work and somehow try and rectify this mess and merge it back into this one, feel free, but I no longer have the time to work on anything RetroArch and TBQH it might be better to just ignore what I did and redo the work here. Best of luck.

**Comment by ToniBC** [comment]
I mentioned it just to keep it in mind, since many of the errors they comment are already fixed in the Standalone version. The same thing that other cores updated, like Fuse, which was very outdated, is touching this one. The later, more updates come out and more work.

Obviously this is done when you can, you don't have to do everything at once, gradually update and that, and when you can, but when you see that it has not been played for so long, it is strange. Some cores are updated a lot and others are abandoned, it is not a criticism, this is done by fan and that, but everything would have to be dosed a bit.

The latest movements and notifications from the team aim to keep the cores up to date, which is fine, but it is rare that being a Saturn that so much affection is had for Sega, it does not update.

**Comment by PoloniumRain** [comment]
Hey @ToniBC it's time for yet another thread title update lol... Mednafen 1.27.1 stable has now been released. 

Being as Beetle Saturn is based on 1.22.2, this core is almost 26 months out of date. 

@hiddenasbestos Was you previously the one doing most of the work on this core? If so, is it practically dead now you can't work on it?

**Comment by ToniBC** [comment]
I have to wake up and all that and then the notifications come to me. The purpose of this thread is to notify or report that the core is very outdated. As programmers say many times, if something is not reported, everything works fine.

If we are reporting the errors we find, no matter how small, we give life to the thread and it is more likely that it will be updated.

The Fuse emulator for example took forever (years) to update.

I suppose that active programmers are focused on other tasks or cores and I imagine that at some point they will review this core.

MAME for example has not been updated for 2 months and some other core more. We just have to be patient.

**Comment by hiddenasbestos** [comment]
> @hiddenasbestos Was you previously the one doing most of the work on this core? If so, is it practically dead now you can't work on it?
That's correct, I've done the previous upgrades from Mednafen. Unfortunately I can't work on this project any more. I hope it's not dead because of that but if there's no other interest from developers to work on it then that's the reality :(

**Comment by ToniBC** [comment]
There are many cores to update and the members of the project focus on what they want. Some may be put to review some core, but there are many backward as Citra, this same, and some more, but others are up to date.

We just have to be patient.

**Comment by Tasosgemah** [comment]
I'm using version 1.24.3 posted above and it's working fine so far. Are there any issues using it over the "official" core that i'm not aware of?

Even that is 1.5 years out of date and missing a bunch of Saturn updates, seeing that the next couple of versions were almost exclusively Saturn fixes. 

I wonder why is this specific core so hard to update over the others. I hope it's not abandoned.

**Comment by ToniBC** [comment]
It is not that it is difficult, it is that there is no one to update it, that is, before it seems that a user was in charge, but it has been a long time that he cannot or does not feel like it, so another has to do it.

In theory it is simple, it is to buy the modules and apply the corrections that are already created, it is not to solve bugs, only to apply the modifications that are already in the standalone. It is something relatively simple, but obviously requires time and desire.

These open source projects are maintained by the community, and of course, having so many cores, it is more complicated. The solution would be to find someone to do core maintenance, not create new stuff, just keep changes up to date.

Hopefully this and others get updated.

**Comment by Tasosgemah** [comment]
Maybe a bounty would help with the desire part then?

**Comment by ToniBC** [comment]
Rewards always help, but I don't know how that works or how they are accepted or assigned. Supporting the project is also essential, that is, projects like Yuzu (Nintendo Switch emulator) get $ 20,000 per month, with more than 5k patreons, but Retroarh only $ 1,500 per month, something ridiculous in comparison, since this system is present on all consoles and laptops, on Android, Mac and all Launchers like Retropie / Emulec / Recalbox / Batocera ...

Supporting projects is essential, it is the boost of encouragement that people need. And as always, this falls within the possibilities of each one, obviously, but without counting the economic, you can collaborate by reporting all the bugs that are found, testing things, etc ... If you play and see that something is wrong, report it if it is not there already reported and that helps.

**Comment by Tasosgemah** [comment]
1.28.0 standalone is out, with plenty of Saturn fixes.

**Comment by ToniBC** [comment]
Well yes, they would have to look at it, Mednafen is little updated, but almost everything is focused on the Saturn emulation. It is the best emulator we have of this system and in Retroarch it adds a plus, but they have abandoned it.

Maybe now that they are fixing them for android as they say, take a look at it a bit.

As it has little movement, the updates are implemented quickly, not like other emulators that update every day.

They would have to find someone to update these cores and improve others.

**Comment by TheNewClassics** [comment]
Does Libretro still do bounties? I was considering putting one in for the Saturn core updates, having a hard time finding where the bounties are located

**Comment by Tasosgemah** [comment]
Yeah, a bounty would be the best solution i think.

**Comment by TheNewClassics** [comment]
Looks like the 1.29 update came out pretty recently

**Comment by TheNewClassics** [comment]
Hey @Tasosgemah , how are you using the 1.24.3 version that hiddenasbestos made? Are you able to use it within RA?

**Comment by Tasosgemah** [comment]
> Hey @Tasosgemah , how are you using the 1.24.3 version that hiddenasbestos made? Are you able to use it within RA?

Yes, that's what i use for a while now.

**Comment by TheNewClassics** [comment]
How do you get it to work within RA as a core? The download on hiddenasbesto's repository seems to be setup like mednafen, rather than an RA core.

**Comment by Tasosgemah** [comment]
hmm i can't remember, probably someone compiled it for me or something. Once i get home i will upload it somewhere and post a link here.

**Comment by Tasosgemah** [comment]
Ok, here it is:

[mednafen_saturn_libretro.zip](https://github.com/libretro/beetle-saturn-libretro/files/7998890/mednafen_saturn_libretro.zip)

**Comment by TheNewClassics** [comment]
Thank you so much @Tasosgemah !

**Comment by wally86** [comment]
> Ok, here it is:
> 
> [mednafen_saturn_libretro.zip](https://github.com/libretro/beetle-saturn-libretro/files/7998890/mednafen_saturn_libretro.zip)

is this 1.29.0? in my retroarch with the core loaded it says 1.24.3.

Thanks

**Comment by Tasosgemah** [comment]
> > Ok, here it is:
> > [mednafen_saturn_libretro.zip](https://github.com/libretro/beetle-saturn-libretro/files/7998890/mednafen_saturn_libretro.zip)
> 
> is this 1.29.0? in my retroarch with the core loaded it says 1.24.3.
> 
> Thanks

Yes, its 1.24.3. Which is still old but a bit newer than the official build version of 1.22. There is no 1.29 version, the core hasn't been updated for years.

**Comment by whitezombie2000** [comment]
The Saturn gets no love...I would love to see this core get updated to 1.29.0. :(

**Comment by PoloniumRain** [comment]
If anyone here doesn't yet know, this core was _finally_ updated to 1.29 a while ago.

But Mednafen [1.31.0-unstable](https://forum.fobby.net/index.php?t=rview&goto=6752&th=2100#msg_6752) has just been released. The biggest change is support for most ST-V games. I wouldn't expect an update to 1.31 anyway though, because it is an 'unstable' version. 1.29 is still the latest stable.

**Comment by Tasosgemah** [comment]
> I wouldn't expect an update to 1.31 anyway though, because it is an 'unstable' version. 1.29 is still the latest stable.

Thesre are these commits though: https://github.com/libretro/beetle-saturn-libretro/commits/master

**Comment by ToniBC** [comment]
Sorry, I forgot to close the issue because I've updated it.

Thanks
