### ISSUE TITLE
Switching control type to Mission Stick or Dual Mission Sticks Registers Random Inputs

### ISSUE THREAD

**Issue by eoc300** [libretro-mirrors/beetle-saturn-libretro#161]
It just starts to press random bottons, I tried it with Panzer Dragoon games and SoukyuGurentai (in Panzer Dragoon seems to register the analog going to the upper left corner).Doesn't happen in mednafen emulator

**Comment by hensez** [comment]
Why is this closed? This seems to be an issue still. Retropad is not properly mapped to emulated mission stick analog axes like the joystick's neutral position was off.
