### ISSUE TITLE
PAL image not centered vertically

### ISSUE THREAD

**Issue by ner00** [libretro-mirrors/beetle-saturn-libretro#164]
I tested a couple PAL games and Beetle Saturn doesn't center the image correctly.
The issue starts immediately at the boot animation and goes on to the game.

Below is an animated gif that shows a comparison between standalone (correct) and libretro (incorrect):
![](https://media.giphy.com/media/ZDDtOwuu2W5h7Zzqaa/giphy.gif)

I am not entirely sure if the issue is tied to the first scanline, but according to Mednafen's documentation the first displayed scanline in PAL mode should be -16, yet libretro's core cannot go below 0, even if you change the value by hand in the cfg, it will just go back to 0.

I was able to mimic the centered positioning seen in standalone by setting first scanline to 9 and last scanline to 278. This shouldn't be correct either though because it should do 255 scanlines (-16 through 271). In any case, 0 through 271 as PAL default doesn't center the output image vertically in libretro.

**Comment by negativeExponent** [comment]
scanline options are configurable for a reason, although i would prefer a simple overscan crop instead but "some" people wants to expose every pixel, evey line that is drawn despite it not suppose to be normally viewable on CRT back then.

in anycase 271 - 16 = 255 in my calculation. so set initial scanline to 16, and last to 271 for PAL content. ignore what you think "mednafen" does or suppose to suggest,
