### ISSUE TITLE
cheat tables (cht) are not working correctly

### ISSUE THREAD

**Issue by eadmaster** [libretro-mirrors/beetle-saturn-libretro#177]
I've tried both the cheats included with the [libretro-database](https://github.com/libretro/libretro-database/tree/master/cht/Sega%20-%20Saturn) and [other sources](https://gamehacking.org/system/sat).

([Also reported here](https://www.reddit.com/r/RetroArch/comments/jmjff2/beetle_saturn_cheat_support/))

If you try to do a manual Cheat Search you'll find that the actual memory address is shifted from the original value in the cht.

**Comment by ExxistanceDC** [comment]
Can confirm this is happening to me as well, with Beetle Saturn and games like Shinobi Legions .

**Comment by eadmaster** [comment]
duplicate of https://github.com/libretro/beetle-saturn-libretro/issues/5
