### ISSUE TITLE
"Per Game" Shared Memory Card Setting Does Not Work

### ISSUE THREAD

**Issue by delta7890** [libretro-mirrors/beetle-saturn-libretro#181]
Setting the Shared Memory Card option to "Per Game" does not work as it should.  Setting this option to "Per Game" has the same effect as setting it to "Shared."

I'd further like to recommend that the "Per Game" option, once fixed, be the default option as this has been the standard behavior in Beetle Saturn up to this point.

**Comment by bslenul** [comment]
Yeah, no matter what the core option is set to, it's like "shared" is always enabled :/ And +1 for the default being "per game", it was always like this before, would be weird to change it now...

**Comment by housello** [comment]
I fixed it and made a new pull request.
It should work fine now, and the default setting is set to "disabled"

**Comment by bslenul** [comment]
Just tried your PR, works like a charm now, thank you for the fix! 👍

**Comment by delta7890** [comment]
I can also confirm that everything is working as intended now.  Thank you!
