### ISSUE TITLE
100% utilization of one CPU core, even when paused

### ISSUE THREAD

**Issue by Sanaki** [libretro-mirrors/beetle-saturn-libretro#188]
When running on Linux, utilization cannot drop below 25% (of four cores) when running, but seems distributed across cores. When pausing retroarch, one CPU core is locked at full utilization. It won't rotate to another CPU core in this state either, which could cause damage on some systems if the user leaves the game paused for an extended period of time. So far as I can tell, no other core exhibits this behavior. The core also gets very poor performance (65-70 fps fast forwarding) despite my system being more than sufficient, which points to this being the potential cause. ~~Others on discord didn't report this behavior on Windows, so I'm guessing it's Linux-specific.~~ @sonninnos has now verified this on Windows as well.

Retroarch 1.9.1 libretro/retroarch@502ecb2d64
Beetle Saturn 47b30b4fc4bdac805261218d942bcadee5479d5f
Linux Mint 19.3 x86_64, kernel 5.4.0-67-generic
CPU: i5-7300HQ

**Comment by jdgleaver** [comment]
This fixes the CPU utilisation issue:  #191

But sadly the overall performance is about the same as before...
