### ISSUE TITLE
Die Hard Trilogy USA won't load past Sega logo

### ISSUE THREAD

**Issue by sjftech** [libretro-mirrors/beetle-saturn-libretro#193]
Hi All, as above.

In either chd or bin/cue format, it won't load past the Sega logo with Mednafen. The European version works, however I'd prefer the USA version because of the faster gameplay. Standalone Mednafen loads the game fine. I think this is due to the age of the version this core is based off, it appears to have not been updated in a long time.

None of the other Saturn cores run this version of the game either as they detect the game as if it's not even a Saturn disc, so this is completely unplayable in Retroarch.

Any ideas?

**Comment by sjftech** [comment]
For the hell of it I tried patching it to the European version and it boots fine but obviously still runs at 50hz. It's a weird glitch.

**Comment by Sanaki** [comment]
I can verify this issue using a Redump-verified dump of the game.
http://redump.org/disc/26655/

**Comment by sjftech** [comment]
Thanks for verifying that, it seems unlikely that this core will get updated to a newer version of Mednafen to fix both this and other issues though so have to move to standalone Mednafen to play this game or play the slower European version.

**Comment by bslenul** [comment]
Thought I answered to this issue, but it was on Reddit :p Anyway, it was fixed in standalone 1.23.0-UNSTABLE, more than a year ago: https://forum.fobby.net/index.php?t=rview&goto=5921&th=1817#msg_5921

They don't have a GitHub? I wanted to try applying the commit that fixed it but I'm not sure how to do that if they don't have one :x

**Comment by sjftech** [comment]
Don't know if this is correct?

https://github.com/mednafen/mednafen.github.io

**Comment by bslenul** [comment]
Unfortunately no, that's for their website, not for the program itself :(

**Comment by sjftech** [comment]
What about this? This looks like an up to date, but untouched mirror of Mednafen.

https://github.com/libretro-mirrors/mednafen-git

**Comment by bslenul** [comment]
That's just mirrors of the sources for each version, but there are no "detailed" commit history for each change, etc. Like it doesn't say "the changes from these files fix the Die Hard issue".

I guess it would be possible to figured it out by comparing 1.22.2 and 1.23.0 sources, but that sounds like a PITA :p

**Comment by sjftech** [comment]
Bah, I give up then lol :)

**Comment by Jackmath5** [comment]
> I can verify this issue using a Redump-verified dump of the game. http://redump.org/disc/26655/

you can?

**Comment by cobhc2019** [comment]
Given up on libretro and everything to do with it.

**Comment by Sanaki** [comment]
This issue isn't resolved. Information on the topic can be found here:
https://old.reddit.com/r/RetroArch/comments/msz0fy/tips_for_getting_the_usa_version_of_die_hard/

This was fixed in Mednafen 1.23.0, but as of this time, no libretro core can run this region of the game.
