### ISSUE TITLE
RetroArch freezes with rewind enabled during boot and load screens

### ISSUE THREAD

**Issue by Sanaki** [libretro-mirrors/beetle-saturn-libretro#194]
When rewind is enabled during boot, RetroArch freezes immediately. It seems there's a second stage when the boot sequence ends where it will freeze if rewind is enabled. Another freeze can trigger during disc access for various games. Leaving RetroAchievements enabled in hardcore mode will disable rewind (at least until the server fails to return a valid achievement set), so doing so can bypass the initial freezes in some cases.

RetroArch 1.9.1 libretro/Retroarch@6b021f8d14
Beetle Saturn f7515829166660a61c6692160bb2b2d2633df9fc
Linux Mint 19.3 x86_64

**Comment by bslenul** [comment]
Bisected, seems to be happening since 209fb86fae853a9b9a39a8ef148e78f4b1572ad5

**Comment by jdgleaver** [comment]
Sorry guys - I don't know how I ended up missing this issue for so long... :(

Should be fixed with this: #197

**Comment by bslenul** [comment]
No problem, you can't be everywhere :D Thanks for the fix, seems to work like a charm! 👍

**Comment by Sanaki** [comment]
Works nicely, thanks.
