### ISSUE TITLE
Running CHD v5 on Android 64bit Still Lacks.

### ISSUE THREAD

**Issue by vus7294** [libretro-mirrors/beetle-saturn-libretro#198]
on Windows 64bit, Perfectly Works. of course CHD. but Android 64bit, it doesn't work at all.
It has Started From my first try in January 2021, and Still Lacks on Android 64bit. (Galaxy S9, Android 10) Thanks.

**Comment by vus7294** [comment]
#159

**Comment by TideGear** [comment]
I can confirm CHDs still don't load. I have a Galaxy s20 Ultra on Android 11. CHDs also don't work when trying to load them in Beetle Saturn on the 32-bit build of RetroArch. I believe this CHD issue is independent from [#159](https://github.com/libretro/beetle-saturn-libretro/issues/159).
