### ISSUE TITLE
Sega rally doesnt start.

### ISSUE THREAD

**Issue by mac1202** [libretro-mirrors/beetle-saturn-libretro#2]
Hi from all the game I got it's the only that doesn't work in the libretro core and work in the standalone mednafen.
Instead of starting the game it open the cd player interface.
http://imgur.com/21KCbT4
log > http://pastebin.com/c27cVC3Z

**Comment by inactive123** [comment]
Works fine here, probably a wrong disc on your end.

**Comment by mac1202** [comment]
Sorry It publish the issue before i finish to write it. 
The cue/bin i got work perfectly with the standalone mednafen.

**Comment by inactive123** [comment]
Good for standalone mednafen then, the version of Sega Rally I found worked just fine.

Let me know in an e-mail where to obtain this from.

I'll research it when I have time.

**Comment by Awakened0** [comment]
I have the same problem with Sega Rally Championship Plus - Netlink Edition. Works fine in stand alone, but shows the Sega logo twice and then goes to the BIOS menu. Selecting "Start Application" from the menu causes it to loop from the Sega logo back to the menu. Should be a good dump. Netlink Edition is supposed to be the best version of the game.

**Comment by inactive123** [comment]
I might have to redo the CD-ROM code again completely from scratch.

**Comment by Awakened0** [comment]
Panzer Dragoon II Zwei also boots me back to the BIOS menu when I try to skip the intro FMV. Not a problem in stand alone.

**Comment by inactive123** [comment]
The isos I have found all work fine for those games. I won't discount there might be problems with the CD-ROM code in the current core but honestly, all these games have worked fine for me on more proper sets (like can be found on IA).

Anyway, stop reporting about this until I have updated the CD-ROM code. Until then, it's just an echo chamber in here. I already know about it.

**Comment by inactive123** [comment]
@Awakened0 - I updated the CD-ROM code now to the latest code, time to try again.

**Comment by mac1202** [comment]
The updated cd-rom code fixed the issue, thanks.

**Comment by Awakened0** [comment]
Confirmed, all the games I was having boot issues with work fine now.

Thanks!
