### ISSUE TITLE
Earthworm Jim 2 pauses when pressing 2 simultaneous opposite directions

### ISSUE THREAD

**Issue by orobas0** [libretro-mirrors/beetle-saturn-libretro#204]
Versions: 
Retroarch (1.9.5)
beetle-saturn-libretro (latest nightly buildbot ver.)
Earthworm Jim 2 (only tested the USA release)
Windows 10 x64

Issue:
While playing Earthworm Jim 2 using Retroarch with the beetle-saturn-libretro core and the keyboard as my controller, whenever I press opposite directions simultaneously (left+right or up+down), the game pauses as if I'd pressed the pause button. I need to keep unpausing the game to play because ending up pressing opposite keys when fast actions are needed is pretty common while using keyboard controls.

I can't reproduce the issue using the mednafen emulator itself (1.27.1) or Retroarch + other Sega Saturn cores, so I suspect this is a beetle-saturn-libretro core issue.

Steps to reproduce the issue:
Load Earthworm Jim 2 in Retroarch using the beetle-saturn-libretro core, start a new game, press left+right in any moment.

Thank you in advance.

**Comment by bslenul** [comment]
The exact same thing happens in PowerSlave, it is super annoying when you're playing on a keyboard 😓

**Comment by bslenul** [comment]
I've submitted a fix few days ago, if you're curious to test: [mednafen_saturn_libretro.zip](https://github.com/libretro/beetle-saturn-libretro/files/7202485/mednafen_saturn_libretro.zip)

It simply adds a core option to enable/disable Up+Down and Left+Right (disabled by default).

**Comment by orobas0** [comment]
Thank you for taking the time to code a workaround yourself. The fix is working properly here!
