### ISSUE TITLE
CUE fails with additional file information

### ISSUE THREAD

**Issue by zach-morris** [libretro-mirrors/beetle-saturn-libretro#23]
Attempting to load a game from a cue file from the command line (or from retroarch GUI) will fail with the game with the following files:
Battle Monsters v1.000 (1996)(Acclaim)(PAL)(Track 1 of 2)[!].iso
Battle Monsters v1.000 (1996)(Acclaim)(PAL)(Track 2 of 2)[!].wav
Battle Monsters v1.000 (1996)(Acclaim)(PAL)[!].cue

The cue file contents is originally as follows:
CATALOG 3455198208016
FILE "Battle Monsters v1.000 (1996)(Acclaim)(PAL)(Track 1 of 2)[!].iso" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00
FILE "Battle Monsters v1.000 (1996)(Acclaim)(PAL)(Track 2 of 2)[!].wav" WAVE
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 00:00:00

Fails to load for the following reason:
RetroArch [libretro WARN] :: Unsupported CUE sheet directive: "CATALOG".
libc++abi.dylib: terminating with uncaught exception of type int

Try 2, change the cue file to:
FILE "Battle Monsters v1.000 (1996)(Acclaim)(PAL)(Track 1 of 2)[!].iso" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00
FILE "Battle Monsters v1.000 (1996)(Acclaim)(PAL)(Track 2 of 2)[!].wav" WAVE
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 00:00:00

Fails to load for the following reason:
libc++abi.dylib: terminating with uncaught exception of type int
Abort trap: 6

Try 3, changed the cue file to:
FILE "Battle Monsters v1.000 (1996)(Acclaim)(PAL)(Track 1 of 2)[!].iso" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00

And that worked.
Suggest allowing for the additional information in the cue file or ignoring it if necessary.

**Comment by andres-asm** [comment]
can you test standalone to verify if the problem is mednafen's?

**Comment by newoski** [comment]
I have no such problems using bin/cue for this game

**Comment by zach-morris** [comment]
Is your cue file the same as first try listed above?

**Comment by newoski** [comment]
No, I am using a bin/cue file combo. No wav/mp3. I'm posting a solution, I'm not trying to imply your problem is solved or unsolved.

( :

**Comment by zach-morris** [comment]
Could this possibly be the same as https://github.com/libretro/beetle-pce-fast-libretro/issues/52 ?

**Comment by hiddenasbestos** [comment]
This core only supports single .bin files when loading from a .cue. Redump into this format from your original disc.
