### ISSUE TITLE
Mouse support not implemented

### ISSUE THREAD

**Issue by ghost** [libretro-mirrors/beetle-saturn-libretro#24]
There is an option to use a mouse in controller settings but it does not respond to your actual mouse. This fuctionality works correctly in upstream Mednafen.

**Comment by hiddenasbestos** [comment]
Hi @gnutechs, I've added support for this in pull request #84

**Comment by hiddenasbestos** [comment]
It would be awesome if you could close this issue if you're happy that it's all working.
