### ISSUE TITLE
Crashes at startup if compiled with GCC 5.2 (mingw)

### ISSUE THREAD

**Issue by andres-asm** [libretro-mirrors/beetle-saturn-libretro#3]
Backtrace
http://hastebin.com/tamiwusilo.xml

IIRC for other mednafen cores you removed vswprintf

**Comment by andres-asm** [comment]
It only happens with logging verbose...
Pretty weird, maybe there is some undefined character somewhere in a log call?

Happens on every version. If I use the buildbot builds (4.9.2) it works fine.

**Comment by orbea** [comment]
For reference.
https://github.com/libretro/beetle-saturn-libretro/pull/4
