### ISSUE TITLE
Update core to 0.9.47

### ISSUE THREAD

**Issue by ofry** [libretro-mirrors/beetle-saturn-libretro#52]
See https://mednafen.github.io/

Mednafen 0.9.47 August 26, 2017 - 02:36 PDT

**Comment by boomercore** [comment]
Is this being worked on at all, or is the aim to wait for a later revision still?  This is an important release, adding save state support and fixing several games that wouldn't boot prior, such as Super Tempo.  Perhaps the save state support is taking some time to implement?

**Comment by vanilsonsantos** [comment]
I'm following this project since the beginning, please continue with this awesome work! Mednafen versions 0.9.47 and 0.9.48 have nice improvements.

**Comment by Tasosgemah** [comment]
I wonder if this project is abandoned. Libretro version is stuck in version 0.9.45 for so long. Because of this some games like Super Tempo don't work like in the official release (it reached 0.9.48 by now, with many Saturn fixes).

**Comment by hiddenasbestos** [comment]
I've just had a small pull request merged, so it's not totally dead :)

**Comment by hiddenasbestos** [comment]
Hi, I'm working on this: https://imgur.com/jvSN0Ax

**Comment by Tasosgemah** [comment]
Hey thanks for your efforts :)

Just a question though. Are you going to update the core to a more recent version (where Tempo works) or you are going to make the game work in the current, older core?

**Comment by hiddenasbestos** [comment]
I've ported across *all* the changes from Mednafen 0.9.46 -> 0.9.47. This also includes super early Action Replay cart support, fixes for several games and save states.

Super Tempo was just something I thought would show the progress, since you specifically mentioned it @Tasosgemah. I'm currently working on integrating save states into libretro API to complete the update.

**Comment by Mr-Jake** [comment]
Thank you @hiddenasbestos for your hard work and effort in updating the core!

0.9.48 has a lot of Saturn game specific bug fixes. Would it be difficult to include this also? If not, I am totally grateful that you are updating to 0.9.47.

**Comment by Tasosgemah** [comment]
Edit: Nvm, my cue files got scrambled for some reason

**Comment by vanilsonsantos** [comment]
Thank you so much @hiddenasbestos ! I really appreciate your hard work!

**Comment by hiddenasbestos** [comment]
You're welcome. It's helping to take each version as an individual step so I'm concentrating on reaching 0.9.47 as a milestone. I'm not against applying further updates in future but it depends on my availability.

**Comment by hiddenasbestos** [comment]
I don't know why that's happening @Tasosgemah. I don't know if my patch would have affected that, there weren't any changes to the CD IIRC. Everything is definitely all still working for me, sorry. FYI I'm building using MSYS2/mingw64 on Windows.

I suppose, create a new issue and see if someone on Linux/mac/what are you running can take a look?

**Comment by Tasosgemah** [comment]
It's OK. For some inexplicable reason some of my cue files got corrupted, having random symbols inside instead of regular text. I don't know why/how this happened, it was all good a day ago, lol. Replaced them from a backup and it's all good but i have no idea what would cause this. The HDD looks fine, no errors whatsoever. Sorry for the derail.

**Comment by hiddenasbestos** [comment]
Save states are done.
https://www.youtube.com/watch?v=WR6991Um28w

It's 1am now, will review/commit when I'm more alert.

**Comment by boomercore** [comment]
Great work, I look forward to trying this.

**Comment by mirrornoir** [comment]
Yeah thanks for all the hard work! I've been following this as I'm extremely excited for these new features, especially save states. I can't wait to try it.

**Comment by hiddenasbestos** [comment]
Okay I think it's working, so I created pull request #67. Guess you can close this :)

**Comment by Tatsuya79** [comment]
Thanks that's great!

**Comment by ofry** [comment]
Big thank you.
