### ISSUE TITLE
Disc Cycle Tray Status seemingly failing to eject virtual discs correctly

### ISSUE THREAD

**Issue by HeyItsLollie** [libretro-mirrors/beetle-saturn-libretro#55]
## Description

Beetle Saturn core seemingly fails to eject virtual discs correctly (Disc Control > Disc Cycle Tray Status), despite RetroArch printing the messages "Ejected/Closed virtual disc tray" as expected, making it impossible to boot into Sega Saturn's system bios, or switch discs via Disc Index.

### Expected behavior

Ejecting disc immediately after launching game, before Sega Saturn boot sequence has played out:
Beetle Saturn should boot into system bios. When playing a multi-disc game (.M3U playlist comprised of multiple .CUE files), Disc Index should become usable.

### Actual behavior

Beetle Saturn continues to boot game. Disc Cycle Tray Status causes RetroArch to print the message "Ejected virtual disc tray" on first use, "Closed virtual disc tray" on second use, but Beetle Saturn acts as if the disc tray is closed regardless of setting.

### Steps to reproduce the bug

1. Load a Sega Saturn game. (any game should be fine, even a single-disc game)
2. Immediately open RetroArch's quick menu.
3. Disc Control > Press "Disc Cycle Tray Status" once. RetroArch should print the message "Ejected virtual disc tray."
4. (optional, but related) Try to increment Disc Index. RetroArch should print the message "Failed to set disc (number out of total discs)." (eg: 1/1, or 2/4, etc)
5. Resume (WITHOUT closing virtual disc tray), and watch as Beetle Saturn continues to boot the game, despite the virtual disc tray supposedly being left open.

### Bisect Results

This is outside my abilities, but judging by these two posts, this issue has been present for at least one year.
- https://forums.libretro.com/t/disk-swapping-issues-saturn-mednafen/6229
- https://github.com/libretro/beetle-saturn-libretro/issues/14

### Version/Commit

- RetroArch: 1.6.7 / 0d06a485 (Nightly for Oct 15, 2017)
- Medafen Saturn v0.9.45.1 (latest version available via Online Updater > Core Update as of Oct 15, 2017)

### Environment information

- OS: Windows 10 Pro (Version 1703) 64-bit

**Comment by ghost** [comment]
I'm not sure it's possible to even reach the BIOS in the standalone version of Mednafen Saturn and I know for a fact that I tried it on Beetle Saturn and got the same result as you, it still loaded the game despite of the disc ejection.

It's nice to be able to enter the BIOS like you can on the real hardware but as far as I know SSF is the only emulator I have used that have managed to pull it off correctly, I can't speak for Yabause or uoYabause though.

I also know for a fact that Beetle PSX does it correctly, eject the disc and restart and you will be able to enter the BIOS and make changes to the memory cards etc. however I'm not sure about the standalone Mednafen PSX.

Might have to try it out tomorrow for shits and giggles.

**Comment by HeyItsLollie** [comment]
I've checked! Saturn BIOS can be opened in standalone Mednafen by using the following [command line](https://mednafen.github.io/documentation/#Section_command_line):

`mednafen.exe -force_module ss -which_medium -1 "<path to cue/m3u>"`

- "_-force_module ss_" does what you'd expect, forcing Mednafen to force the Sega Saturn module. As far as I could tell, the codes for all (or most) possible modules are included in Mednafen's [Table of Contents](https://mednafen.github.io/documentation/), under "Emulation Module Documentation."
- "_-which_medium -1_" tells Mednafen to boot with the disc in its ejected state.
- For whatever reason, a disc path must be provided when booting to BIOS, though the disc itself doesn't matter, as it will be immediately ejected. You can literally use a PS1 .cue while forcing the Sega Saturn BIOS to load, and vice versa.

All said, the important part here is that the disc should be ejectable. RetroArch literally cannot swap discs for multi-disc Saturn games unless the Beetle Saturn core correctly ejects them first.

**Comment by ghost** [comment]
Nice, I guess you can do the same for PSX and PC-Engine too.

**Comment by ghost** [comment]
@HeyItsLollie 

It worked perfectly with all three modules (pce, psx and ss) and I even created my own no_disc.bin and no_disc.cue files for the sole purpose of getting into the BIOS.

The no_disc.bin is completely empty and the no_disc.cue is filled with dummy data, meaning fake tracks and linking to the no_disc.bin just to get it going.

Only problem was the pce module, I couldn't get into the CD-Player interface it just said "Just a moment..." after I pushed the Run button.

I know it's possible to get into the CD-Player interface because many many years ago when I used MagicEngine it worked.

**Comment by retro-wertz** [comment]
disk swapping option has disabled for this core. hope someone can look into it and hook it up again. this is way out of my league :D

**Comment by hiddenasbestos** [comment]
Pull request #95 .. requested. Hope this helps :)

**Comment by hiddenasbestos** [comment]
Hi, if this is working now, would be awesome if you could close this issue - it helps keep things tidy :)

**Comment by HeyItsLollie** [comment]
Found some time to do a little testing (using _Policenauts_), and compared to Mednafen standalone, Beetle Saturn seems to be working as expected now. The core kicks itself back to the Saturn bios when the disc tray has been opened, and switching discs works correctly.

Thank you for implementing this!
