### ISSUE TITLE
screen flickering and retroarch crashing when loading interlaced content.

### ISSUE THREAD

**Issue by ghost** [libretro-mirrors/beetle-saturn-libretro#64]
When loading cdimages that is using interlaced modes, screen flickering occurs.
~~Switching to fullscreen or opening menu crashes retroarch too.~~

Dark Savior (EU) and Sega Touring Car Championship (E)

upstream do not have similar issue.

**Comment by retro-wertz** [comment]
crashing should be fixed with this commit : https://github.com/libretro/beetle-saturn-libretro/pull/65

screen flickering is still a problem though.
