### ISSUE TITLE
Virtua Gun / Stunner support

### ISSUE THREAD

**Issue by hiddenasbestos** [libretro-mirrors/beetle-saturn-libretro#79]
I've started work on support for the Virtua Gun lightgun  #78  . However I've hit a bit of a brick wall, so I'm posted this issue with hopes that my work will at least give people an advantage in fixing this some day.

**Comment by ghost** [comment]
what problem specifically? i managed to get virtua gun to work, at least for virtua cop 2 (u) using default video parameters..  

![screenshot_2017-11-18_18-24-41](https://user-images.githubusercontent.com/23315382/32979337-53338708-cc8e-11e7-9171-ed94d16631a7.png)

the possible problem i can think of is if we need to compensate for overscan changes, but should still can work.

**Comment by hiddenasbestos** [comment]
Hi @retro-wertz, I'm glad you took a look at this. When I posted this issue you'd hover over the bad guys and click the mouse and it would act like you were shooting off screen and never hit anything - it was very frustrating. But I've just tried it again with no changes, just a sync to latest master revision, and it works!! I credit you for this - either your backport of 0.9.45 or your overscan work - whatever you did behind the scenes it's working properly now :)

So the remaining issues are:

1. The scaling from libretro pointer position into Saturn co-ordinates are just hacked in with arbitrary scaling factors. I think you'd be much better placed to debug where the real scaling factors should come from - I hate that it's hardcoded to 240 lines, that's totally going to break on PAL games, and the X scaling is just a magical fudge factor with no obvious basis in reality. I only did this to try and make progress with the trigger problem, but then I gave up :)

2. I feel like we should be using the RETRO_DEVICE_LIGHTGUN api for this thing, but I'm forced to use RETRO_DEVICE_POINTER since mednafen (and I assume most hardware) wants an absolute value but the lightgun API gives you relative like a mouse, which doesn't seem right to me.

3. RetroArch's RETRO_DEVICE_POINTER implementation reports a central position as default when the mouse cursor is outside of the application window (or in fullscreen if you move the cursor to a second monitor). That's kind of unhelpful and I wish it gave back a negative position, or some other magic number, for this condition. This might be a separate job in and of itself. We also need to handle the 'off-screen' condition for lightgun hardware that doesn't report it.

Although mouse support is now in, and it maybe feels like less of a priority to support this peripheral, it would be very cool to use a Wiimote / Dolphin-bar combo with RetroArch to play Saturn or PS1 lightgun games imo. I'm not sure how far along gun support is in PS1 land, also are there any other cores that support lightguns? I know a ton of old platforms had them.

**Comment by ghost** [comment]
udev driver/winraw should support wiimote/dolphin bar and multiple mice
input, but i have no way to confirm it working on my side.

virtua gun code expects pointer-type device so using device_pointer is the
way to go unless you want to code absolute type stuff in using
device_mouse/lightgun to piggy-back data from(or something). then use
device_mouse for buttons since pointer only has 1 button. also, kindly add
joypad_start as the alternate start button as you may not believe it, but
im just using a 2-button mouse :D

**Comment by hiddenasbestos** [comment]
Oh yeah good point -- on a 3 button mouse you have to press middle and right and that's no fun either tbh !!!  I've just pushed an update with mouse 4/5 (sorry!)  and joypad start button both working as light-gun start button (same as Saturn mouse peripheral support)

**Comment by ghost** [comment]
actually, for virtua gun there are only 3 buttons, trigger, an emulated offscreen shot, and pause/start. start is middle button only.

**Comment by hiddenasbestos** [comment]
It was my understanding that RETRO_DEVICE_ID_LIGHTGUN_START is activated with middle+right mouse buttons pressed together. At the moment you can't remap that to something more sensible which is a bit frustrating. I guess I've only got myself to blame since I'm working on the fringes :)

In an ideal world I'd like to just use the lightgun API - but right now it doesn't seem practical. Same goes for the mouse start button mapped to joypad start, that seems messy to me but I realise you need to be accommodating of people using semi-incompatible hardware when you're emulating something.

Hopefully my latest patch makes it a bit easier to look into Virtua Cop problems if you wish to.

**Comment by hiddenasbestos** [comment]
Fixed in #89 !

**Comment by ghost** [comment]
i am not really undestanding the idea for button mapping for this. theres only 3 buttons needed(including an already programmed emulated offscreen shot button) typical mouse it 3 buttons. my pc version virtua cop2 if i remembered correctly has right-click(for right-handed people) has been reload button.  not getting the idea why we really need to duplicated code to emulate offscreen shot by actually moving the pointer offscreen(which is really inconvenient especially for window-mode users)....

**Comment by hiddenasbestos** [comment]
If you'd like to play Virtua Cop 1 or 2 with a mouse, then why not set the core to use a mouse? That sets it up with right click for reload, left click to shoot and start to pause - just like the PC version.

The real experience of using a light-gun is you have to aim off-screen to reload - which is what I've emulated (there's no fake off-screen shot any more). It's supposed to be inconvenient!

**Comment by ghost** [comment]
there is a difference in the movement using device_mouse and device_pointer
which was i prefer using pointer in similar implementation if possible.

so ok, we are emulating convenience then.. nice...

**Comment by hiddenasbestos** [comment]
How about we create a different type of light-gun that is designed for and works much better with a mouse?  "Virtua Gun (mouse)" perhaps?

This way you can have the authentic experience if you have the equipment to do so (Aimtrak or Dolphin Bar, etc.) but if you'd like to play with a mouse then you can switch it to this new device type and it'll be setup to have a fake off-screen on the right mouse button, left button to shoot and then retropad start to pause?

**Comment by hiddenasbestos** [comment]
You might be interested in a lightgun proposal I'm discussing here https://github.com/libretro/libretro-common/issues/51  remapping lightgun inputs in RetroArch will be one of goals of this too I think.

**Comment by hiddenasbestos** [comment]
Hi @retro-wertz - I've submitted pull requests to add the ability to completely remap mouse buttons used for light guns. This lets you create a Virtua Cop 2 PC experience on a mouse and lets me use my Dolphin bar with its different bindings.
