### ISSUE TITLE
CHD breaks 'NiGHTS Into Dreams' (specifically)

### ISSUE THREAD

**Issue by hiddenasbestos** [libretro-mirrors/beetle-saturn-libretro#83]
I compressed all my games into CHD format using:
"chdman - MAME Compressed Hunks of Data (CHD) manager 0.148 (Feb  4 2013)"

This included a bin/cue version of 'NiGHTS Into Dreams' (US). In CHD format the game soft-locks with a black screen straight after the usual published/licensed to SEGA screen, before the Sonic Team intro video. 

I've (so far) encountered no other problems with any other games compressed using this tool. 
NOTE: If I use the 'extractcd' command to turn the CHD back into a CUE/BIN, it works again. So presumably there's a problem with the decompression of CHD data?

**Comment by Awakened0** [comment]
You should probably be using the latest chdman that comes with the MAME binary package, since they've improved the format over time. But, even with the latest chdman, I also had this issue when CHD support was first added. It was a problem with the dump. The 2016 (USA) (RE) Redump version worked fine.

**Comment by hiddenasbestos** [comment]
I don't want to be awkward but I think if the dump works in BIN/CUE mode it should work as a CHD - it's supposed to be lossless compression so shouldn't it be feeding the same data into the CD bus of the Saturn? Apologies that I don't know what is going on internally for CHD but I think it should be consistent (or at the very least print a warning in the log.)

**Comment by Awakened0** [comment]
Back when CHD was first implemented, @rtissera said it's probably something to do with a bad TOC: https://github.com/libretro/beetle-saturn-libretro/issues/31#issuecomment-319306471

**Comment by hiddenasbestos** [comment]
Cheers, happy to close this then.
